# Generated by Django 5.2.3 on 2025-06-30 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_city', models.CharField(blank=True, max_length=100)),
                ('default_country', models.CharField(blank=True, max_length=10)),
                ('default_unit', models.CharField(choices=[('metric', 'Metric (°C)'), ('imperial', 'Imperial (°F)')], default='metric', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
