# Generated by Django 5.2.3 on 2025-06-30 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='default_theme',
            field=models.CharField(choices=[('light', 'Light'), ('light-dark', 'Light Dark'), ('dracula', 'Dracula'), ('high-contrast', 'High Contrast'), ('sepia', 'Sepia')], default='light', help_text='Visual theme applied on first page load.', max_length=20),
        ),
        migrations.AlterField(
            model_name='favoritelocation',
            name='city_name',
            field=models.CharField(help_text="Name of the city, e.g. 'London'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='favoritelocation',
            name='country_code',
            field=models.CharField(blank=True, help_text="Optional 2-letter ISO country code, e.g. 'GB'.", max_length=10),
        ),
        migrations.AlterField(
            model_name='favoritelocation',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this favorite was added.'),
        ),
        migrations.AlterField(
            model_name='favoritelocation',
            name='user',
            field=models.ForeignKey(help_text='The user who saved this location.', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preference',
            name='default_city',
            field=models.CharField(blank=True, help_text='City to auto-load when no search term is given.', max_length=100),
        ),
        migrations.AlterField(
            model_name='preference',
            name='default_country',
            field=models.CharField(blank=True, help_text='Optional ISO country code to pair with default_city.', max_length=10),
        ),
        migrations.AlterField(
            model_name='preference',
            name='default_unit',
            field=models.CharField(choices=[('metric', 'Metric (°C)'), ('imperial', 'Imperial (°F)')], default='metric', help_text='Temperature unit: metric (°C) or imperial (°F).', max_length=10),
        ),
        migrations.AlterField(
            model_name='preference',
            name='user',
            field=models.OneToOneField(help_text='The user this preference set belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL),
        ),
    ]
